### PR TITLE
feat/tokenSeparator property added

### PR DESCRIPTION
**Pull request by LeopoldBriand**

### CODE REVIEW

**Comment by shayneo** [comment]
Thank you @LeopoldBriand ! Will get this merged soon, my son had surgery last week so I've been tied up with that. Should be able to get this in the next few days 😄

**Comment by LeopoldBriand** [comment]
Thank you for your time and responsiveness !

**Comment by LeopoldBriand** [comment]
Is that could be done this week ?

**Comment by shayneo** [comment]
This is live and published in v 2.2.0! https://github.com/shayneo/vue-fuse/releases/tag/2.2.0

Thanks again

**Pull request merged**
